### ISSUE TITLE
Extra big font at mobile version of site

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1834]
Firefox 80.1.3

![](https://bitbucket.org/repo/b6qGGA/images/3286891495-Screenshot_20200919-232043.png)
‌

[Issue created by Bujno: 2020-09-19]

**Comment by MarkitkaM** [comment]
Sometimes there are bigger fonts, I guess because the website has no mobile version and for better visibility. Maybe for a purpose.
![chrome_cfP35tj2ek](https://user-images.githubusercontent.com/88401908/132951027-24baafdc-ecf9-4222-9333-7e6f9e580fd1.png)
![chrome_n9YI8UONcW](https://user-images.githubusercontent.com/88401908/132951032-481dfda8-d323-47d4-ada6-12b5325ff881.png)
![chrome_ttMRxtIJLv](https://user-images.githubusercontent.com/88401908/132951033-183c6f41-761c-46a7-9d49-8f3b9459b869.png)

**Comment by MarkitkaM** [comment]
The new website https://new.isthereanydeal.com/ has a mobile version already.
