### ISSUE TITLE
"Try ITAD Alpha" link breaks top bar functionality in Safari

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1964]
The link to the ITAD Alpha breaks the functionality of the top bar by straddling two lines. This breaks the functionality of the top bar by making it unable to change regions, deal with notifications, or use the search functionality.

By removing the CSS flexbox attribute on the link, the link uses one line instead, and those functionalities can be used.
![chrome_3R2DjO07E7](https://user-images.githubusercontent.com/88401908/131290063-380386f4-65a5-4ded-89c9-09fac9ca8d7b.png)

[Issue created by [deleted]: 2021-01-04]

**Comment by cbirdsong** [comment]
> By removing the CSS flexbox attribute on the link, the link uses one line instead, and those functionalities can be used.

Adding `vertical-align: middle;` to the `<img>` tag fixes the layout after doing this.

**Comment by MarkitkaM** [comment]
I checked Mac and iPad on BrowserStack, multiple resolutions, and versions of iOS and Safari.  All Looks and works well.

Via screenshot - similar resolution as the screenshot of the user:
![chrome_P4JO0D1r8a](https://user-images.githubusercontent.com/88401908/131292223-3bac0993-2921-44a5-8d88-d9dca3f3d289.png)

**Comment by sarahlicity** [comment]
> I checked Mac and iPad on BrowserStack, multiple resolutions, and versions of iOS and Safari. All Looks and works well.
> 
> Via screenshot - similar resolution as the screenshot of the user:
> ![chrome_P4JO0D1r8a](https://user-images.githubusercontent.com/88401908/131292223-3bac0993-2921-44a5-8d88-d9dca3f3d289.png)

The issue isn't on the alpha site; the issue is on the main site.

**Comment by MarkitkaM** [comment]
My apologies. Now I can see the problem on https://isthereanydeal.com/.
I tested:
- iOS - IPad mini 3 Safar
-  MAC - Big Sur, Catalina, Mojave

1. Difficulties or impossible to change region - depends on the version
2. Not possible to use the search bar because the top bar dropping the sub-navigation  down

Video created on Mac - Catalina
https://youtu.be/-RgQDt5AW8c
![chrome_qbTX4LNFzl](https://user-images.githubusercontent.com/88401908/134029914-dd9015f8-e5a8-4db4-8c9a-170684a42ceb.png)

**Comment by MarkitkaM** [comment]
Hi,
the new website is being prepared for the full process so this bug will be not fixed.
We apologize for any inconvenience caused by this problem.
