### ISSUE TITLE
Duplicate: God of War

### ISSUE THREAD

**Issue by ghost** [IsThereAnyDeal/IsThereAnyDeal-Issues#3083]
When I click on the "view on ITAD" button from augmented steam on the store page it sends me to link #1 which is a duplicate. It seems like there are some duplicates that get created that have the game title but doubled, and the ones that have the doubled name only have the art logo, but the ones with the correct name have everything but the art logo. There was another game I saw this happen with but I do not remember which one it was.

(1) https://isthereanydeal.com/game/godofwargodofwar/info/
(2) https://isthereanydeal.com/game/godofwar/info/

**Comment by andrew-hill** [comment]
I'm seeing the same with a few games that synced from my Steam wishlist, where the 'double-name' version of the game has been added to my ITAD waitlist when synchronising my steam wishlist.

This redundant/incorrect version of the game gives no prices, history, etc. Even when switching to other regions (i thought maybe it was a regional difference in naming somehow).

Occasionally they match up to show reviews (see Ender Lilies below) but often it's a completely redundant and incorrect page (the ones with the name repeated).

Also these duplicated/incorrectly named games don't show up in the search results on ITAD, so perhaps there's already some flagging or checking there that's aware they're incorrect/broken pages.

Examples that synced incorrectly from Steam:

https://isthereanydeal.com/game/eldenringeldenring/info/
vs https://isthereanydeal.com/game/eldenring/info/

https://isthereanydeal.com/game/vampiresurvivorsvampiresurvivors/info/
vs https://isthereanydeal.com/game/vampiresurvivors/info/

https://isthereanydeal.com/game/cultoflambcultoflamb/info/
vs https://isthereanydeal.com/game/cultoflamb/info/

This one is slightly different, as it's not just a duplicated name but seems to be a full vs shortened name (with/without the subtitle):
https://isthereanydeal.com/game/enderliliesquietusofknights/info/
vs https://isthereanydeal.com/game/enderlilies/info/

As an experiment, I tried duplicating some names of other games on my list (where it had correctly synchronised with Steam and chosen the correct game for my ITAD wishlist) and found some other examples below. Though most of the time there's no duplicate-name version of most games.

Duplicated
- https://isthereanydeal.com/game/factoriofactorio/info/ vs https://isthereanydeal.com/game/factorio/info/

Alternate Names
- https://isthereanydeal.com/game/finalfantasyviiremake/info/ vs https://isthereanydeal.com/game/finalfantasyviiremakeintergrade/info/

So this suggests to me it's not purely a steam sync issue, since it's picked the 'right' game in those cases, while there exists an incorrect version.

**Comment by MarkitkaM** [comment]
Duplication #3044
Entries to merge #2324
