### ISSUE TITLE
ECHO is reporting prices for wrong games.

### ISSUE THREAD

**Issue by NJC2** [IsThereAnyDeal/IsThereAnyDeal-Issues#3127]
I just got a notice of a low price for the game [ECHO](https://store.steampowered.com/app/551770/ECHO/), but the link is to the store page of a game called [Echoes](https://store.steampowered.com/app/1610060/).  Looking at the games Info Page, there are four Steam prices, GOG and itch.io.  The GOG and one of the Steam links are correct, the others go to completely different games.

_Edited to fix link._

**Comment by jheuck** [comment]
Same issue here...

The 4 different Steam games have VERY slight variations in their titles:

* [ECHO](https://store.steampowered.com/app/551770/ECHO/) - A$29.99 (The one I'm after, and the one shown in [this ITAD page](https://isthereanydeal.com/game/echo/info/). Both the Steam and GOG prices are listed.)
* [Echoes](https://store.steampowered.com/app/1610060/Echoes/) - A$7.50
* [echo](https://store.steampowered.com/app/1992410/echo/) - A$11.50
* [Echo](https://store.steampowered.com/app/2100420/Echo/) - A$50.95

Obviously very easy to get these confused (in fact it looks like even the OP might have accidentally linked "echo" instead of "ECHO" in his comment!!)

**Comment by NJC2** [comment]
> Obviously very easy to get these confused (in fact it looks like even the OP might have accidentally linked "echo" instead of "ECHO" in his comment!!)

Yes, that first link in my post should be to [ECHO](https://store.steampowered.com/app/551770/ECHO/) not echo.  I've edited it to fix the link.

**Comment by MarkitkaM** [comment]
Entries to split #2323
