### ISSUE TITLE
DLC Filter for owned games

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#409]
Hi,

like i wrote on reddit - 

it would be cool to have a filter that shows all available unpurchased DLCs for games that you own.

[Issue created by [deleted]: 2016-01-29]

**Comment by MarkitkaM** [comment]
Already possible 
![image](https://user-images.githubusercontent.com/88401908/139583452-46013927-3624-485a-866f-51cd3196a06c.png)

**Comment by qs-arno** [comment]
I just tried this filter myself and it's working as expected (it's showing DLCs that aren't in my collection).  However, it's not filtering based on the base game.  In other words, it's showing _all_ DLCs I don't own, regardless of whether I own the base game or not.  Am I missing something?

Actually, it looks like this issue is a duplicate of https://github.com/IsThereAnyDeal/IsThereAnyDeal-Issues/issues/2526 so I'll just follow that issue instead.  GAME OFF
